### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Error: 401 Unauthorized

### ISSUE THREAD

**Issue by tonydavis629** [npgrosser/Houston#2]
I am suddenly unable to run hu commands, resulting in this error. Here is the full stack trace

```
Exception in thread "main" java.lang.IllegalStateException: Error: 401 Unauthorized
        at de.npgrosser.houston.openai.OpenAi$completions$1.invokeSuspend(OpenAi.kt:72)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at de.npgrosser.houston.openai.OpenAi.completions(OpenAi.kt:65)
        at de.npgrosser.houston.generator.OpenAiScriptGenerator$generate$1.invoke(OpenAiScriptGenerator.kt:61)
        at de.npgrosser.houston.generator.OpenAiScriptGenerator$generate$1.invoke(OpenAiScriptGenerator.kt:61)
        at de.npgrosser.houston.utils.FileBasedCache.loadOrCompute(Cache.kt:54)
        at de.npgrosser.houston.generator.OpenAiScriptGenerator.generate(OpenAiScriptGenerator.kt:61)
        at de.npgrosser.houston.commands.HuCommand.run(HuCommand.kt:239)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at de.npgrosser.houston.commands.HuCommandKt.main(HuCommand.kt:289)
```

**Comment by npgrosser** [comment]
Looks like you should double check if your OpenAI key is correctly set and valid

**Comment by tonydavis629** [comment]
I had it set to an old key, thanks
